# Generated by Django 4.1.2 on 2022-11-28 09:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('drawn', models.BooleanField(default=False)),
                ('drawn_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'ball',
                'verbose_name_plural': 'balls',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('won_ambo', models.BooleanField(default=False)),
                ('won_terno', models.BooleanField(default=False)),
                ('won_quaterna', models.BooleanField(default=False)),
                ('won_cinquina', models.BooleanField(default=False)),
                ('won_tombola', models.BooleanField(default=False)),
                ('card', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=9), size=3)),
            ],
            options={
                'verbose_name': 'card',
                'verbose_name_plural': 'cards',
                'ordering': ['card_id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=6, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('numero_matricola', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('numero_di_cartelle', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_win', models.CharField(choices=[('NOTHING', 'Nothing'), ('AMBO', 'Ambo'), ('TERNA', 'Terna'), ('QUATERNA', 'Quaterna'), ('CINQUINA', 'Cinquina'), ('TOMBOLA', 'Tombola')], default='NOTHING', max_length=255)),
                ('won_at', models.DateTimeField(null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.player')),
            ],
            options={
                'verbose_name': 'winner',
                'verbose_name_plural': 'winners',
                'ordering': ['type_of_win', 'won_at'],
            },
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination', models.CharField(choices=[('NOTHING', 'Nothing'), ('AMBO', 'Ambo'), ('TERNA', 'Terna'), ('QUATERNA', 'Quaterna'), ('CINQUINA', 'Cinquina'), ('TOMBOLA', 'Tombola')], default='NOTHING', max_length=255)),
                ('won', models.BooleanField(default=False)),
                ('won_at', models.DateTimeField(null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.player')),
            ],
            options={
                'verbose_name': 'combination',
                'verbose_name_plural': 'combinations',
                'ordering': ['combination'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.player'),
        ),
    ]
