version: "3.9"

services:
  app:
    build: .
    restart: always
    command: "/scripts/docker/starter.sh"
    env_file:
      - ./.env
    depends_on:
      - database
    expose:
      - 8000
    volumes:
      - ./volumes/static:/core/staticfiles
      - ./volumes/media:/core/mediafiles

  nginx:
    build: ./nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
      - "443:443"
    volumes:
      - ./volumes/static:/staticfiles
      - ./volumes/media:/mediafiles
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
      - database

  database:
    image: postgres:16.0
    restart: always
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
    env_file:
      - ./.env
