services:
  app:
    build: .
    restart: always
    command: "/scripts/docker/starter.sh"
    env_file:
      - ./.env
    depends_on:
      - database
    expose:
      - 8000
    volumes:
      - static_volume:/vol/staticfiles
      - media_volume:/vol/mediafiles

  database:
    image: postgres:16.0
    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
    env_file:
      - ./.env

  caddy:
    build: ./caddy
    restart: always
    ports:
      - ${CADDY_PORT}:80
      - "443:443"
    volumes:
      - static_volume:/vol/staticfiles
      - media_volume:/vol/mediafiles
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${CADDY_EMAIL}

volumes:
  static_volume:
  media_volume:
