# COMBINATIONS VALUES
NOTHING = 'NOTHING'
AMBO = 'AMBO'
TERNA = 'TERNA'
QUATERNA = 'QUATERNA'
CINQUINA = 'CINQUINA'
TOMBOLA = 'TOMBOLA'

COMBINATIONS_CHOICES = (
    (NOTHING, 'Nothing'),
    (AMBO, 'Ambo'),
    (TERNA, 'Terna'),
    (QUATERNA, 'Quaterna'),
    (CINQUINA, 'Cinquina'),
    (TOMBOLA, 'Tombola'),
)


# NUMBER OF WINNERS FOR EACH COMBINATION
AMBO_WINNERS = 20
TERNA_WINNERS = 20
QUATERNA_WINNERS = 20
CINQUINA_WINNERS = 20
TOMBOLA_WINNERS = 20
